CREATE TABLE San
(
	MaSan CHAR(3) PRIMARY KEY,
	TenSan NVARCHAR(50),
	DiaChi NVARCHAR(100)
)

CREATE TABLE Doi
(
	MaDoi CHAR(3) PRIMARY KEY,
	TenDoi NVARCHAR(20),
	MaSan CHAR(3),
	FOREIGN KEY (MaSan) REFERENCES San(MaSan)
)
CREATE TABLE TranDau
(
	MaTD INT PRIMARY KEY,
	MaSan CHAR(3),
	Ngay DATE,
	Gio TIME,
	FOREIGN KEY (MaSan) REFERENCES San(MaSan)
)

CREATE TABLE CT_TranDau
(
	MaTD INT,
	MaDoi CHAR(3),
	SoBanThang INT CHECK (SoBanThang >= 0),
	PRIMARY KEY (MaTD, MaDoi),
	FOREIGN KEY (MaTD) REFERENCES TranDau(MaTD),
	FOREIGN KEY (MaDoi) REFERENCES Doi(MaDoi)
)
