CREATE TABLE MAYBAY
(
	MaMB INT PRIMARY KEY,
	Loai VARCHAR(50),
	TamBay INT,
)

CREATE TABLE CHUYENBAY
(
	MaCB CHAR(5) PRIMARY KEY,
	GaDi VARCHAR(50),
	GaDen VARCHAR(50),
	DoDai INT,
	GioDi TIME,
	GioDen TIME,
	ChiPhi INT,
	MaMB INT,
	FOREIGN KEY (MaMB) REFERENCES MAYBAY(MaMB)
)

CREATE TABLE NHANVIEN
(
	MaNV CHAR(9) PRIMARY KEY,
	Ten NVARCHAR(50),
	Luong INT
)

CREATE TABLE CHUNGNHAN
(
	MaNV CHAR(9),
	MaMB INT,
	PRIMARY KEY(MaNV, MaMB),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	FOREIGN KEY (MaMB) REFERENCES MAYBAY(MaMB)
)
